spring:
  application:
    name: BloomSchool

  datasource:
    url: jdbc:postgresql://localhost:5432/bloom_school_db
    username: user1
    password: user1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 9090
  shutdown: GRACEFUL