package com.bloom.bloomschool.fees.entity;

import com.bloom.bloomschool.common.entity.BaseEntity;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * One itemized, snapshotted charge billed to a student off a specific APPROVED FeeStructure
 * version. Generated by FeeService.generateCharges when a structure is approved (and lazily
 * backfilled by getCurrentCharges for structures approved before this entity existed) — never
 * mutated afterward, so history stays auditable across structure revisions. Snapshots
 * itemName/category/amount rather than joining live to FeeItem, so a later catalog edit or
 * deletion never changes what a student was actually charged.
 */
@Entity
@Table(name = "bloom_sch_student_fee_charges")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class StudentFeeCharge extends BaseEntity {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true, updatable = false)
    private UUID uuid;

    @PrePersist
    public void generateUuid() { if (uuid == null) uuid = UUID.randomUUID(); }

    @Column(nullable = false)
    private UUID studentUuid;

    /** Admission number — the join key FeePayment already uses as `studentId`. */
    @Column(nullable = false)
    private String admissionNumber;

    private String studentName;

    @Column(nullable = false)
    private String grade;

    private String stream;

    @Column(nullable = false)
    private UUID feeStructureUuid;

    @Column(nullable = false)
    private int structureVersion;

    @Column(nullable = false)
    private int academicYear;

    /** FeeStructure.term at generation time — "Term 1"/"Term 2"/"Term 3"/"Full Year". */
    @Column(nullable = false)
    private String period;

    private Long itemId;

    @Column(nullable = false)
    private String itemName;

    @Enumerated(EnumType.STRING)
    private FeeCategory category;

    @Column(nullable = false)
    private double amount;

    private LocalDate dueDate;

    @Column(nullable = false)
    private LocalDateTime generatedAt;
}
